export const GET_CATEGORYES = "GET_CATEGORYES";
export const GET_CARDS = "GET_CARDS";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_LOADING = "SET_LOADING";
export const SET_CART_ITEMS = "SET_CART_ITEMS";